-- PERMISOS DE SUPER USUARIO (EJECUTAR DESDE / as sysdba)
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;
CREATE USER "WILL" identified by root;

-- crear usuario con permisos de creacion/edicion
GRANT CREATE SESSION TO "WILL" WITH ADMIN OPTION;

GRANT CREATE TABLE TO "WILL";
GRANT ALTER ANY TABLE TO "WILL";